name: core
description: A flarum application by Flutter.

version: 1.0.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  shared_preferences: ^0.5.8
  dio: ^3.0.10
  cached_network_image: ^2.2.0+1
  gesture_zoom_box: ^0.0.3
  path_provider: ^1.6.11
  html: ^0.14.0+3
  font_awesome_flutter: ^8.8.1
  flutter_custom_tabs: ^0.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
